---

- name: instalar la ultima version de Apache en CentOS
  yum: name=httpd state=latest
  when: ansible_os_family == "RedHat"

- name: instalar la ultima version de Apache en Ubuntu
  apt: name=apache2 state=latest
  when: ansible_os_family == "Debian"

- name: Levantar Servicio httpd
  service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- name: Levantar Servicios Apache2
  service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- name: Abrir puertos http y https
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - https
  when: ansible_os_family == "RedHat"
  notify:
  - name: Reiniciar el firewall

- name: Permitir puertos 80 y 443 en Ubuntu
  ufw:
    rule: allow
    port: '80,443,22'
    proto: tcp
    state: enabled
  when: ansible_os_family == "Debian"

- name: Crear Directorios
  file:
    path: /var/www/html/demo.com
    state: directory

- name: Copia de archivos para servidor Centos
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'demo.com.conf',dest: '/etc/httpd/conf.d'}
    - { src: 'index.html',dest: '/var/www/html'}
    - { src: '/root/repos/playbook/webservers/files/demo/index.html',dest: '/var/www/html/demo.com'}
  when: ansible_os_family == "RedHat"

#- name: Copia de archivos para servidor Ubuntu
#  copy:
#    src: "{{ item.src }}"
#    dest: "{{ item.dest }}"
#  with_items:
#    - { src: 'demo.com.conf',dest: '/etc/apache2/conf-available'}
#    - { src: 'index.html',dest: '/var/www/html'}
#    - { src: '/root/repos/playbook/webservers/files/demo/index.html',dest: '/var/www/html/demo.com'}
#  when: ansible_os_family == "Debian"


...

# tasks file for webservers
